// Design tokens & shared style helpers — LiberVault

export const C = {
  bg:         "#060A0F",
  surface:    "#0B1018",
  surfaceHi:  "#0F1822",
  border:     "#0F1E2E",
  borderLit:  "#1A3A55",
  text:       "#C5DCF0",
  dim:        "#4A7A9B",
  blue:       "#00C8FF",
  blueDim:    "#0077A8",
  blueGlow:   "rgba(0,200,255,0.10)",
  green:      "#00E5A0",
  red:        "#FF3A5C",
  amber:      "#FFB020",
  // Chain colors
  eth:        "#627EEA",
  btc:        "#F7931A",
  sol:        "#9945FF",
  dot:        "#E6007A",
  lib:        "#22C997",
  xmr:        "#FF6600",  // Monero orange
} as const;

export const F = "'JetBrains Mono', monospace";

export const S = {
  screen: {
    display: "flex" as const,
    flexDirection: "column" as const,
    flex: 1,
    overflow: "hidden" as const,
  },
  scrollBody: {
    flex: 1,
    overflowY: "auto" as const,
    padding: "14px 18px 20px",
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: 12,
  },
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: 10,
    padding: "11px 14px",
  },
  input: {
    width: "100%",
    background: C.surface,
    border: `1px solid ${C.borderLit}`,
    borderRadius: 8,
    padding: "10px 14px",
    fontFamily: F,
    fontSize: 12,
    color: C.text,
    outline: "none",
  },
  label: {
    fontSize: 9,
    fontWeight: 700 as const,
    letterSpacing: "0.14em",
    color: C.dim,
    textTransform: "uppercase" as const,
    display: "flex" as const,
    alignItems: "center" as const,
    gap: 5,
    marginBottom: 5,
  },
  btnPrimary: {
    width: "100%",
    background: C.blue,
    color: "#000",
    border: "none",
    borderRadius: 8,
    padding: "11px",
    fontFamily: F,
    fontSize: 11,
    fontWeight: 700 as const,
    letterSpacing: "0.1em",
    cursor: "pointer",
    textTransform: "uppercase" as const,
  },
  btnGhost: {
    width: "100%",
    background: "transparent",
    color: C.text,
    border: `1px solid ${C.borderLit}`,
    borderRadius: 8,
    padding: "10px",
    fontFamily: F,
    fontSize: 11,
    fontWeight: 500 as const,
    letterSpacing: "0.08em",
    cursor: "pointer",
    textTransform: "uppercase" as const,
  },
  tag: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: 5,
    fontSize: 9,
    fontWeight: 600 as const,
    letterSpacing: "0.12em",
    padding: "3px 8px",
    borderRadius: 4,
    border: "1px solid",
  },
  errBox: {
    background: "rgba(255,58,92,0.08)",
    border: "1px solid rgba(255,58,92,0.3)",
    borderRadius: 8,
    padding: "8px 12px",
    fontSize: 10,
    color: "#FF3A5C",
    fontFamily: F,
  },
};

export const CHAIN_META = [
  { key: "evm",       label: "Ethereum",  sym: "ETH", color: C.eth, note: ""                    },
  { key: "bitcoin",   label: "Bitcoin",   sym: "BTC", color: C.btc, note: ""                    },
  { key: "solana",    label: "Solana",    sym: "SOL", color: C.sol, note: ""                    },
  { key: "polkadot",  label: "Polkadot",  sym: "DOT", color: C.dot, note: ""                    },
  { key: "liberland", label: "Liberland", sym: "LLD", color: C.lib, note: " · LLD + LLM"        },
  { key: "monero",    label: "Monero",    sym: "XMR", color: C.xmr, note: " · spend + view keys" },
] as const;
